# Prod version - Буду еще править
version: '3.3'
services:

  db:
    image: postgres:14.2-alpine

    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  frontend:
    # image: godleib/foodgram_frontend:latest
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  
  backend:
    # image: godleib/foodgram_back:v0.2
    build:
      context: ../backend
      dockerfile: Dockerfile
    volumes:
      - static:/app/static/
      - media:/app/media/
      # Мб все таки так
      # - static_value:/var/html/static/
      # - media:/var/html/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.6
    # 1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

      - static:/var/html/static/
      - media:/var/html/media/
    depends_on: 
      - backend
      - frontend

volumes:
  static:
  media:
  dbdata: 