# Prod version - Буду еще править

# https://habr.com/ru/company/flant/blog/336654/ - читшит
# https://habr.com/ru/company/first/blog/592321/

version: '3.3'

services:
  db:
    image: postgres:14.2-alpine

    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    # ports:
    #   - "5432:5432"

  frontend:
    image: godleib/foodgram_frontend:latest
    # build:
    #   context: ../frontend
    #   dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
  
  backend:
    image: godleib/foodgram_backend:latest
    # build:
    #   context: ../backend
    #   dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/app/static-backend/
      - media_value:/app/media-backend/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.6
    # 1.19.3
    ports:
      - "80:80"
      # - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

      - static_value:/var/html/static-backend/
      - media_value:/var/html/media-backend/
    restart: always
    depends_on: 
      - backend
      - frontend

volumes:
  static_value:
  media_value:
  dbdata: 