# Local testing
version: '3.3'
services:

  db:
    image: postgres:14.2-alpine

    volumes:
      - dbdata:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.6
    # 1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/

      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on: 
      # - backend
      - frontend

volumes:
  static_value:
  media_value:
  dbdata:
