# Generated by Django 4.0.3 on 2022-04-09 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['id'], 'verbose_name': 'ингредиенты', 'verbose_name_plural': 'Ингредиент'},
        ),
    ]
