# Generated by Django 4.0.3 on 2022-03-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_ingredientinrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=12.0, upload_to='recipes/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
